# Generated by Django 5.1 on 2024-09-22 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctor_specialization_appointment_doctor_specialties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialties',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.specialization'),
        ),
    ]
