# Generated by Django 5.1 on 2024-09-22 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_doctor_specialties_doctor_specialties'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date')},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='available_dates',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialties',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.specialization'),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='location',
        ),
    ]
