# Generated by Django 5.1 on 2024-09-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_doctor_experience_alter_doctor_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
