# Generated by Django 5.1 on 2024-09-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_doctor_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='qualification',
        ),
    ]
