# Generated by Django 5.1 on 2024-09-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_doctor_fees_remove_doctor_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='fees',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
