# Generated by Django 5.1 on 2024-09-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_doctor_description_doctor_fees_doctor_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialties',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(to='myapp.specialization'),
        ),
    ]
